IEEESB/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/urls.py
from home import views
from django.conf.urls import url
from .models import events
import os
import urllib.request as urllib
app_name = 'home'
from bs4 import BeautifulSoup

import requests
# base_url = "https://gitcdn.link/cdn/KarthikRaja2k1/ieeesb_public/master/home_templates/"
# if(requests.get(base_url+'check.html').content.decode('utf-8')!='404: Not Found'):
#     template_folder='home/templates/'
#     files=os.listdir(template_folder)

#     for file in files:
#         f=open(template_folder+file,"r+")
#         s=""
#         html_content=requests.get(base_url+file)
#         f.write(html_content.content.decode("utf-8"))

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about$', views.about, name='about'),
    url(r'^past_events$', views.past_events, name='past_events?perPage=100'),
    url(r'^upcoming_events$', views.upcoming_events, name='upcoming_events'),
    url(r'^upcoming_events/(?P<event_id>[0-9]+)/$', views.event_page_base, name='details'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^gallery$', views.gallery_images, name='gallery_images'),
    url(r'^base$', views.base, name='Base')
]

home/models.py
from django.db import models

class events(models.Model):
    name = models.CharField(max_length=500)
    start_date = models.DateField()
    type = models.IntegerField()
    coord = models.CharField(max_length=500, default='NIL')
    host = models.IntegerField()
    stream = models.IntegerField()
    speakers = models.CharField(max_length=500, default='NIL')
    no_of_participants = models.IntegerField(default=-1)
    duration = models.IntegerField()
    brochure_link = models.CharField(max_length=300, default='NIL')
    schedule_link = models.CharField(max_length=300, default='NIL')
    event_photo = models.CharField(max_length=100, default='NIL')
    scope = models.CharField(max_length=1000, default='NIL')
    objective = models.CharField(max_length=1000, default='NIL')
    perks = models.CharField(max_length=1000, default='NIL')
    registration_link = models.CharField(max_length=1000, default='NIL')
    registration_fee_ieee = models.FloatField(default=-1)
    registration_fee_non_ieee = models.FloatField(default=-1)
    note = models.CharField(max_length=10000, default='NIL')

    def __str__(self):
        return 'Name :' + self.name

class gallery(models.Model):
    photo_number = models.IntegerField(default=-1)
    title = models.CharField(max_length=100, default='NIL')
    description = models.CharField(max_length=500, default='NIL')

home/views.py
from datetime import date, datetime
from django.shortcuts import render, get_object_or_404
from .models import events
from .models import gallery
import requests
import os
from home.updater import changer
# Create your views here.
global_wrapper=''
def index(request):
    file='index.html'
    changer(file)
    event = list(events.objects.filter(start_date__gte=datetime.now()).order_by('start_date')[:5])
    return render(request,global_wrapper+file, {'events': event})

def about(request):
    file='about.html'
    changer(file)
    return render(request,global_wrapper+file, {'events' : events.objects.all()})

def past_events(request):
    file='past_events.html'
    changer(file)
    event = events.objects.filter(start_date__lt = datetime.now()).order_by('-start_date')
    return render(request,global_wrapper+file, {'events' : event})

def upcoming_events(request):
    file='upcoming_events.html'
    changer(file)
    event = events.objects.filter(start_date__gte = datetime.now()).order_by('start_date')
    return render(request,global_wrapper+file, {'events' : event})

def contact(request):
    file='contact.html'
    changer(file)
    return render(request,global_wrapper+file)

def gallery_images(request):
    file='gallery.html'
    changer(file)
    return render(request,global_wrapper+file, {'images':gallery.objects.all()})

def event_page_base(request, event_id):
    file='event_page_base.html'
    changer(file)
    event = get_object_or_404(events, pk=event_id)
    return render(request, global_wrapper+file, {'events':event})

def base(request):
    file='base.html'
    changer(file)
    return render(request,"Page not found error!!")

home/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block homelink %}../{% endblock %}
{% block homelink1 %}../{% endblock %}
{% block upcoming %}../upcoming_events{% endblock %}
{% block upcoming1 %}../upcoming_events{% endblock %}
{% block homelink2 %}/{% endblock %}
{% block past %}../past_events{% endblock %}
{% block about %}../about{% endblock %}
{% block gallery%}../gallery{% endblock %}
{% block contact %}../contact{% endblock %}
{% block about_active %}class = "active"{% endblock %}
{% block content %}
    <section style="background-repeat: no-repeat; opacity: 0.65; background-size: cover; background-image: url('{% static 'assets/images/back3.jpg' %}');
     " id="banner">
                    <div class="inner">

						<header>
							<h2>About</h2>
						</header>
					</div>

    </section>

    <script>
        function getURL() {
            alert("The URL of this page is: " + window.location.href);
        }
        </script>
        <style>
            .contents{
                margin-top:15%;
            }
            p{
                font-size: 1.4rem;
            }
            .mission_content{
                list-style-type: disc;
                text-align: start;
                padding:8%;
                font-size:1.4rem;
            }
            .branch_society{
                margin-top: 7%;
            }
            .contents li{
                margin-top:0.5rem;
            }
        </style>

    <article id="main" style="margin-top: -10%;">
      <header class="special container">
          <div class="contents">
            <h2><strong>About IEEE</strong></h2>
            <p>IEEE is the world’s largest technical professional organization for the advancement 
                of technology. IEEE and its members inspire a global community to innovate for a 
                better tomorrow through highly cited publications, conferences, technology standards,
                 and professional and educational activities. IEEE is the trusted “voice” for engineering, 
                 computing, and technology information around the globe.</p>
            <br><br>
          </div>
          <div class="contents">
            <h2><strong>SSN IEEE Student Branch</strong></h2>
            <p>The IEEE student Branch of Sri Sivasubramaniya Nadar College of Engineering was formed on 
                2nd May 1998. SSN IEEE Student Branch has been very active and vibrant till this date. 
                The Student Branch was started with 10 student members in 1998. Every year the number of 
                student members joined in IEEE has increased and presently the Branch has 200+ members. 
                Since then, it has organized many events to provide outstanding value to its members. 
                The objective of starting IEEE Student branch was to create awareness about the day-to-day 
                technological developments and to make them to utilize the resources available in IEEE. 
                And to make most of our student members involve themselves in publishing research papers and projects.</p>
            <br><br>
          </div>
          <div class="contents">
            <h2><strong>Vision</strong></h2>
            <p>To Inspire, Enable, Empower and Energize our student members to enhance their technical interests by providing 
                them a platform to show case their skills.</p>
            <br><br>
          </div>
         <div class="contents">
            <h2><strong>Mission</strong></h2>
            <br>
            <ul class="mission_content">
                <li>Work towards inspiring more students to become members.</li>
                <li>Increase the Membership Retention, through the benefits of IEEE.</li>
                <li>Organize technical awareness programs for young professionals.</li>
                <li>Form more Special Interest Groups to encourage project activity among the student members.</li>
                <li>Kindle students’ interest in making new papers and projects.</li>
                <li>Strive towards achieving more IEEE-sponsored awards and aim at representing papers in international conferences.</li>
                <li>Impart sound knowledge of specific domains to the students.</li>
                <li>Nurture students to build information systems for the benefit of society.</li>
                <li>Empower students with the knowledge in the emerging research areas.</li>
            </ul>
            <br><br>
         </div>
         <h2><strong>Student Branch Societies</strong></h2>
                   <div class="branch_society">
            <img style="height: 250px; width: 200px;" src="{% static 'assets/logo/ieee-cs.png' %}">
          <h4><strong>Computer Society</strong></h4>
          <p class="text-justify">The IEEE Computer Society is the premier source for information, inspiration, and collaboration in computer science and engineering. </p>
         <br>
         </div>
         <div class="branch_society">
            <img style="height: 250px; width: 200px;" src="{% static 'assets/logo/ieee-embs.png' %}">
          <h4><strong>Engineering in Medicine and Biology Society (EMBS)</strong></h4>
          <p class="text-justify">Your global connection to the world of biomedical engineering</p>
          <p class="text-justify">IEEE Engineering in Medicine and Biology Society (EMBS) is the world’s largest
international society of biomedical engineers.</p>
          <br>
         </div>
          <div class="branch_society">
            <img style="height: 200px; width: 110px;" src="{% static 'assets/logo/ieee-comsoc.png' %}">

          <h4><strong>IEEE ComSoc</strong></h4>
          <p class="text-justify">IEEE Communication Society</p>
          <p class="text-justify">IEEE ComSoc is a leading global community comprised of a diverse group of industry professionals with a common interest in advancing all communications technologies. </p>
          </div>
          <br>
          <div class="branch_society">
            <img style="height: 75px; width: 90px;" src="{% static 'assets/logo/IEEE WIE.jpg' %}">

          <h4><strong>IEEE Women In Engineering</strong></h4>
          <p class="text-justify">IEEE Women in Engineering (WIE) is one of the largest international professional organizations dedicated to promoting women engineers and scientists and inspiring girls around the world to follow their academic interests to a career in engineering.</p>
        </div>
        <br><br>
        <h2><strong>Quick Info</strong></h2>
          <div class="branch_society">
            <table class="info_table">
                <tbody>
                <tr>
                    <td class="bold_info">Date of formation</td>
                    <td></td>
                    <td>2 May 1998</td>
                </tr>
                <tr>
                    <td class="bold_info">Initial Strength</td>
                    <td></td>
                    <td>10</td>
                </tr>
                <tr>
                    <td class="bold_info">Present Strength</td>
                    <td></td>
                    <td>200+</td>
                </tr>
                <tr>
                    <td class="bold_info">Student Branch Code</td>
                    <td></td>
                    <td>STB60551</td>
                </tr>
                <tr>
                    <td class="bold_info">Student Branch Chapters</td>
                    <td></td>
                    <td>Yes</td>
                </tr>
                <tr>
                    <td class="bold_info">Student Branch Library</td>
                    <td></td>
                    <td>Yes</td>
                </tr>
                <tr>
                    <td class="bold_info">Home Page</td>
                    <td></td>
                    <td>https://www.ssn.edu.in/</td>
                </tr>
                <tr>
                    <td class="bold_info">E-mail</td>
                    <td></td>
                    <td>sb.ssnieee@gmail.com</td>
                </tr>
                <tr>
                    <td class="bold_info">Newsletter Activities	</td>
                    <td></td>
                    <td>Yes</td>
                </tr>
                <tr>
                    <td class="bold_info">Awards</td>
                    <td></td>
                    <td>Yes</td>
                </tr>
                </tbody>
            </table>
          </div>
          <br>
      </header>
    </article>
{% endblock %}
ck %}

home/templates/event_page_base.html
{% extends 'base.html' %}
{% load static %}
{% block homelink %}../../{% endblock %}
{% block homelink1 %}../../{% endblock %}
{% block upcoming %}../../upcoming_events{% endblock %}
{% block upcoming1 %}../../upcoming_events{% endblock %}
{% block homelink2 %}/{% endblock %}
{% block past %}../../past_events{% endblock %}
{% block about %}../../about{% endblock %}
{% block gallery%}../../gallery{% endblock %}
{% block contact %}../../contact{% endblock %}
{% block event_active %}class = "active"{% endblock %}
{% block content %}

    <section style="background-repeat: no-repeat; opacity: 0.65; background-size: cover; background-image: url('{% static 'assets/images/back3.jpg' %}');
     " id="banner">
                    <div class="inner">

						<header>
							<h2>{{ events.name }}</h2>
						</header>
					</div>

    </section>
    <article id="main">
       <header style="margin-top: -400px;" class="special container">

           {% if events.event_photo != 'NIL' %}
                {% static "assets/images/events" as baseUrl %}
               <img style="height: auto; width: 80%;" src="{{ baseUrl }}/{{ events.event_photo }}">
           {% endif %}
            <br><br>
           <p><strong><span style="font-size: 40px;">{{ events.start_date }}</span><br><br></strong></p>
           {% if events.registration_link != 'NIL' %}
               <p><strong><span style="font-size: 30px;">Register <a target="_blank" href="{{ events.registration_link }}">here.</a></span><br><br></p>
           {% endif %}
           {% if events.scope != 'NIL' %}
               <p><strong><span style="font-size: 40px;">Scope</span><br><br></strong> {{ events.scope|safe }}</p>
           {% endif %}
           {% if events.brochure_link != 'NIL' %}
               <p><strong><span style="font-size: 40px;">Brochure</span><br><br></strong></p>

               {% static "assets/images/events" as baseUrl %}
               <img style="height: auto; width: 80%;" src="{{ baseUrl }}/{{ events.brochure_link }}">
           {% endif %}
           {% if events.note != 'NIL' %}
               <p><strong><span style="font-size: 40px;">Other Information</span></strong><br><br> {{ events.note|safe }}</p>
           {% endif %}
       </header>
    </article>
{% endblock %}

home/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block homelink %}../{% endblock %}
{% block homelink1 %}../{% endblock %}
{% block upcoming %}../upcoming_events{% endblock %}
{% block upcoming1 %}../upcoming_events{% endblock %}
{% block past %}../past_events{% endblock %}
{% block about %}../about{% endblock %}
{% block homelink2 %}/{% endblock %}
{% block gallery%}../gallery{% endblock %}
{% block contact %}../contact{% endblock %}
{% block gallery_active %}class = "active"{% endblock %}
{% block content %}
    <section style="background-repeat: no-repeat; opacity: 0.65; background-size: cover; background-image: url('{% static 'assets/images/back3.jpg' %}');
     " id="banner">
                    <div class="inner">

						<header>
							<h2>Gallery</h2>
						</header>
					</div>

    </section>
    <br><br><br>
    <div style="text-align: center">
    {% for item in images %}
        {% static "assets/gallery" as baseUrl %}
        <a href="{{ baseUrl }}/{{item.photo_number}}.jpg" data-lightbox="image"><img style="height: 200px; width: 400px;" class="lazy" data-lightbox="image{{ item.id }}" data-original="{{ baseUrl }}/{{item.photo_number}}.jpg" />
        </a>
    {% endfor %}
    </div>

{% endblock %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block homelink %}/{% endblock %}
{% block homelink1 %}/{% endblock %}
{% block homelink2 %}/{% endblock %}
{% block upcoming %}/upcoming_events{% endblock %}
{% block upcoming1 %}/upcoming_events{% endblock %}
{% block past %}/past_events{% endblock %}
{% block about %}/about{% endblock %}
{% block gallery%}/gallery{% endblock %}
{% block contact %}/contact{% endblock %}
{% block home_active %}class = "active"{% endblock %}
{% block content %}
    <div style="background-repeat: no-repeat; opacity: 0.65; background-image: url('{% static 'assets/images/back2.jpg' %}'); background-size: contain;" id="page-wrapper">
                <section id="banner">
                	<div class="inner">

						<header>
							<h2>SSN IEEE Student Branch</h2>
						</header>
						<p style="font-weight: bolder; font-size: 25px;">Welcome to SSN IEEE Student Branch
						<footer>
							<ul class="buttons vertical">
                                <li><a style="width: 30%; background-color: transparent; color: #ffffff; text-shadow: 2px 2px black; opacity: 0.8;" href="#main" class="button scrolly">Dive In</a></li>
							</ul>
						</footer>

					</div>

				</section>
        <article id="main">
                    <div class="row">
                        <div class="col col-sm-1 col-md-2 col-lg-2 col-xs-1 col-xl-2">

                        </div>
                        <div class="col col-sm-10 sol-md-8 col-lg-8 colxs-10 col-xl-8">
                            <video controls poster="{% static 'assets/images/banner.png' %}">
                        <source src="{% static 'assets/video/IEEE -- Promo Video.mp4' %}" type='video/mp4'>
                            </video>
                        </div>
                        <div class="col col-sm-1 col-md-2 col-lg-2 col-xs-1 col-xl-2">

                        </div>

                    </div>
                    <section class="wrapper style2 container special-alt">
							<div class="row 50%">
								<div class="12u 12u(narrower)">

									<header>
										<h2 style="text-align: center; font-weight: 900; font-size: larger;">Recent News</h2>
									</header>
									<div class="marquee" style="font-weight: 900;">
                                        <ol>
                                            <li>
                                                    <header class="marquee-header"><strong><h1 class="marquee-center">Ms. Ruba M, Co- Secretary, SSN IEEE student branch, has been selected as an IEEEXtreme 11.0
                                                        Student Ambassador – 2017.</h1></strong></header></li>
                                            <br>
                                                <li>
                                                    <header class="marquee-header"><strong><h1 class="marquee-center">Mr. Mathirajan E, Publicity Incharge, SSN IEEE student branch, has been selected as a delegate
for the sponsorship by Madras Section to attend AISYWC-2017 being held at IIIT Allahabad
during 27-30 Sep 2017.</h1></strong></header>
                                                </li>
                                            <br>
                                            <li>
                                                    <header class="marquee-header"><strong><h1 class="marquee-center">IEEE Madras Section appreciated our college for our active participation in the year 2016 and classified our college as Grade "A".</h1></strong></header>
                                                </li>
                                            <br>
                                                <li>
                                                    <header class="marquee-header"><strong><h1 class="marquee-center">Mr. Kavin D, Chair, SSN IEEE student branch, has been selected as a Digital Marketing Coordinator in R10 Student Activities Committee Team. </h1></strong></header>
                                                </li>
                                            <br>


                                        </ol>
                                    </div>
                                    <br><br><br>
                                    <footer style="text-align: center;">
									</footer>

								</div>
							</div>
						</section>
                    <header class="special container">
                        <h2><strong>About SSN</strong></h2>
						<p class="text_justify">SSN Institutions, founded by Padma 
							Bhushan Dr. Shiv Nadar, Chairman, HCL Technologies, stands 
							out as a premier centre of higher learning with a mission of 
							pursuing excellence in education and research. The institutions 
							are named after the Chairman’s father Sri Sivasubramaniya Nadar. 
							The institutions, with their diverse and dynamic community of 
							students offer a distinctive combination of some of the finest 
							graduate, undergraduate and research programs, accomplished 
							faculty, world class facilities and a residential campus set on a 
							sprawling 230 acres of sylvan surroundings. While students at 
							SSN immerse themselves in academics, the college has a lot in 
							store for them outside the classroom. Student life includes 
							participation in sports, recreational, co-curricular and cultural 
							activities. In short, at SSN, students will find an academic and 
							social environment where everyone- from faculty members to peers 
							helps shape their future.</p>
                        <br>
                        <br>
                        <h2><strong>About IEEE</strong></h2>
                        <p class="text_justify">IEEE is the world’s largest technical professional 
							organization for the advancement of technology. IEEE and its members 
							inspire a global community to innovate for a better tomorrow through highly 
							cited publications, conferences, technology standards, and professional and 
							educational activities. IEEE is the trusted “voice” for engineering, 
							computing, and technology information around the globe.</p>
					</header>

					<!-- One -->
						<section class="wrapper style2 container special-alt">
							<div class="row 50%">
								<div class="12u 12u(narrower)">

									<header>
										<h2 style="text-align: center; font-weight: 900; font-size: larger;">Upcoming Events</h2>
									</header>
									<div class="marquee" style="font-weight: 900;">
                                        <ol>
                                        {% if not events %}
                                            <li><p class="marquee-center">No Upcoming Events. Check after some time.</p></li>
                                        {% endif %}
                                            {% for item in events %}
                                                <li>
                                                    <header class="marquee-header"><strong><h1 class="marquee-center"><a href="{% url 'home:details' item.id %}">{{ item.name }}</a></h1></strong></header>
                                                <p class="marquee-center">{{ item.start_date }}</p>
                                                <p class="marquee-center" id="hosts{{ item.id }}"></p>
                                                    {% if item.registration_link != 'NIL' %}
                                                    <p class="marquee-center">Register here: {{ item.registration_link }}</p>
                                                    {% else %}
                                                         <p class="marquee-center">On Spot Registration.</p>
                                                    {% endif %}
                                                </li>
                                                <script>
                                                var host = ["Department of Information Technology", "Computer Science Department",
                                                    "Chemical Department", "Mechanical Department", "Bio-Medical Department", "ECE Department",
                                                    "EEE Department", "Civil Department", "IEEE SB"];
                                                var hostingDepartment = host[{{ item.host }}];
                                                var item_id = {{ item.id }};
                                                var idName = "hosts" + item_id;
                                                document.getElementById(idName).innerHTML += hostingDepartment;
                                                </script>
                                                <br><br>

                                            {% endfor %}

                                        </ol>
                                    </div>
                                    <br><br><br>
                                    <footer style="text-align: center;">
										<ul class="buttons">
											<li><a href="/upcoming_events" class="button">Find Out More</a></li>
										</ul>
									</footer>

								</div>
							</div>
						</section>

					<!-- Two -->

					<!-- Three -->
						<section style="margin-top: -8%;" class="wrapper style3 container special">
							<header class="major">
								<h2>QUICK LINKS</h2>
							</header>

							<div class="row">
								<div class="4u 12u(narrower)">


									<section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="https://www.ieee.org/index.html" target="_blank" class="button">IEEE Official Site</a></li>
								            </ul>
										</header>
										<p>Get to know IEEE by visiting their official site.</p>
									</section>
                                    <br>
                                    <section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="http://sites.ieee.org/indiacouncil/" target="_blank" class="button">IEEE India Council</a></li>
								            </ul>
										</header>
										<p>Know about IEEE India Council.</p>
									</section>
                                    <br>
                                    <section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="http://www.ieeer10.org/" target="_blank" class="button">IEEE REGION 10</a></li>
								            </ul>
										</header>
										<p>Know about IEEE Region 10.</p>
									</section>



								</div>
								<div class="4u 12u(narrower)">
                                    <section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="https://www.ieee.org/membership_services/membership/join/index.html?WT.mc_id=hc_join" target="_blank" class="button">Join IEEE</a></li>
								            </ul>
										</header>
										<p>Join IEEE today and make a difference.</p>
									</section>
                                    <br>

                                    <section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="https://www.ieeemadras.org/" target="_blank" class="button">IEEE Madras Section</a></li>
								            </ul>
										</header>
										<p>Visit the home page of one of the most active section of IEEE.</p>
									</section>


								</div>
                                <div class="4u 12u(narrower)">

									<section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="http://ieeexplore.ieee.org/Xplore/home.jsp" target="_blank" class="button">IEEE Xplore</a></li>
								            </ul>
										</header>
										<p>Visit IEEE's Digital Library.</p>
									</section>
                                      <br><br>
                                    <section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="http://spectrum.ieee.org/" target="_blank" class="button">IEEE Spectrum</a></li>
								            </ul>
										</header>
										<p>Know more about the flagship magazine by IEEE.</p>
									</section>
                                    <section>
										<header>
                                            <ul class="buttons quicklinks">
									        <li><a href="https://www.ieee.org/standards/index.html" target="_blank" class="button">IEEE Standards</a></li>
								            </ul>
										</header>
										<p>Know more about IEEE.</p>
									</section>

								</div>
							</div>

							<footer class="major">
								<ul class="buttons">
									<li><a href="http://www.ieee.org/sitemap.html?WT.mc_id=mn_smap" target="_blank" class="button">See More</a></li>
								</ul>
							</footer>

						</section>

				</article>
    </div>
{% endblock %}

home/templates/upcoming_events.html
{% extends 'base.html' %}
{% load static %}
{% block homelink %}../{% endblock %}
{% block homelink1 %}../{% endblock %}
{% block upcoming %}../upcoming_events{% endblock %}
{% block upcoming1 %}../upcoming_events{% endblock %}
{% block homelink2 %}/{% endblock %}
{% block past %}../past_events{% endblock %}
{% block about %}../about{% endblock %}
{% block gallery%}../gallery{% endblock %}
{% block contact %}../contact{% endblock %}
{% block event_active %}class = "active"{% endblock %}
{% block content %}
     <section style="background-repeat: no-repeat; opacity: 0.65; background-size: cover; background-image: url('{% static 'assets/images/back3.jpg' %}');
     " id="banner">
                    <div class="inner">

						<header>
							<h2>Upcoming Events</h2>
						</header>
					</div>

    </section>
      <article id="main">
      <header style="margin-top: -400px;" class="special container">
         {% for event in events %}
             <div class="eventsBox">
                 <p style="margin-top: 20px; max-width: 300px; word-wrap:break-word;">{{ event.name }}</p>
                 <p>{{ event.start_date }}</p>
                 {% if event.registration_link != 'NIL' %}
                 <p>Register <a link="{{ event.registration_link }}">here</a>.</p>
                 {% endif %}
                 {% if event.registration_link == 'NIL' %}
                     <p>On Spot Registration</p>
                 {% endif %}
                 <a href="{% url 'home:details' event.id %}"><button style="width: 200px; background-color: #ffffff; color: black" class="button">More Info</button></a>
             </div>
             {% empty %}
             No Events as of now. Please check after some time.
         {% endfor %}
      </header>
    </article>
{% endblock %}